---
- name: Print massage from master
  ansible.builtin.debug:
    msg:
    - "Running on {{ hostvars[inventory_hostname].tags.Name }}"
    
- name: installing jenkins 1/7
  become: true
  shell: sudo apt-get update -y

- name: installing jenkins 2/7
  become: true
  shell: sudo apt install docker.io -y

- name: installing jenkins 3/7
  become: true
  shell: sudo systemctl start docker

- name: installing jenkins 4/7
  become: true
  shell: sudo usermod -aG docker ubuntu

- name: installing jenkins 5/7
  become: true
  shell: mkdir -p /home/ubuntu/jenkins_home

- name: installing jenkins 6/7
  become: true
  shell: sudo chown -R 1000:1000 /home/ubuntu/jenkins_home

- name: installing jenkins 7/7
  become: true
  shell: sudo docker run -d --restart=always -p 8080:8080 -p 50000:50000 --env JENKINS_ADMIN_ID=admin --env JENKINS_ADMIN_PASSWORD=Banana321! dvaturi/jenkins-srv:latest

- name: Copy github ssh key to known hosts on jenkins server 1/1
  become: true
  shell: sudo ssh-keyscan github.com | tee -a ~/.ssh/known_hosts

- name: installing aws cli 1/1
  become: true
  shell: sudo apt-get install awscli -y

- name: installing kubectl 1/2
  become: true
  shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.17/bin/linux/amd64/kubectl

- name: installing kubectl 2/2
  become: true
  shell: sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: installing helm 1/3
  become: true
  shell: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

- name: installing helm 2/3
  become: true
  shell: chmod 700 get_helm.sh

- name: installing helm 3/3
  become: true
  shell: ./get_helm.sh -v v3.8.2

- name: copy consul-jenkins-server template
  template:
    dest: /etc/consul.d/jenkins-server.json
    src: jenkins-server.json.j2
    force: yes
    owner: consul
    group: consul
    mode: '0755'
  notify: "restart consul service"