---
- name: installing elasticsearch gpg key
  become: true
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add 

- name: Installing Elasticsearch repository
  become: true
  shell: sudo apt-add-repository "deb https://artifacts.elastic.co/packages/8.x/apt stable main"

- name: installing updates
  become: true
  shell: sudo apt-get update -yqq

- name: installing filebeat
  become: true
  shell: sudo apt-get install -yqq filebeat

- name: Copy filebeat conf file
  ansible.builtin.copy:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    force: yes
    owner: root
    group: root
    mode: '0644'
  notify: "restart filebeat service"
