---
- name: Print massage from master
  ansible.builtin.debug:
    msg:
    - "Running on {{ hostvars[inventory_hostname].tags.Name }}"
    
- name: installing jenkins 1/7
  become: true
  shell: sudo apt-get update -y

- name: installing jenkins 2/7
  become: true
  shell: sudo apt install docker.io -y

- name: installing jenkins 3/7
  become: true
  shell: sudo systemctl start docker

- name: installing jenkins 4/7
  become: true
  shell: sudo usermod -aG docker ubuntu

- name: installing jenkins 5/7
  become: true
  shell: mkdir -p /home/ubuntu/jenkins_home

- name: installing jenkins 6/7
  become: true
  shell: sudo chown -R 1000:1000 /home/ubuntu/jenkins_home

- name: installing jenkins 7/7
  become: true
  shell: sudo docker run -d --restart=always -p 8080:8080 -p 50000:50000 -v /home/ubuntu/jenkins_home:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock --env JAVA_OPTS='-Djenkins.install.runSetupWizard=false' jenkins/jenkins