---
- name: installing elasticsearch gpg key
  become: true
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add 

- name: Installing Elasticsearch repository
  become: true
  shell: sudo apt-add-repository "deb https://artifacts.elastic.co/packages/8.x/apt stable main"

- name: installing elasticsearch
  become: true
  shell: sudo apt-get update -yqq

- name: installing elasticsearch
  become: true
  shell: sudo apt-get install -yqq elasticsearch

- name: Copy jvm.options conf file
  ansible.builtin.copy:
    src: jvm.options
    dest: /etc/elasticsearch/jvm.options
    force: yes
    owner: root
    group: root
    mode: '0644'

- name: Copy elasticsearch.yml conf file
  ansible.builtin.copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    force: yes
    owner: root
    group: root
    mode: '0644'

- name: enable elasticsearch service
  become: true
  shell: sudo systemctl enable elasticsearch

- name: start elasticsearch service
  become: true
  shell: sudo systemctl start elasticsearch
    
- name: copy consul-elasticsearch template
  template:
    dest: /etc/consul.d/elasticsearch.json
    src: elasticsearch.json.j2
    force: yes
    owner: consul
    group: consul
    mode: '0755'
  notify: "restart consul service"