filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/syslog
output.logstash:
  enabled: true
  ssl.enabled: false
  hosts: ["logstash.service.opsschool.consul:5044"]
  filebeat.config.modules.path: /etc/filebeat/modules.d/*.yml
  reload.enabled: false