filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/syslog
    - /var/log/auth.log
    - /var/log/jenkins/jenkins.log
    - /var/log/grafana/grafana.log
    - /var/log/prometheus.log
    - /var/log/consul/consul.log
output.logstash:
  enabled: true
  ssl.enabled: false
  hosts: ["logstash.service.opsschool.consul:5044"]
  filebeat.config.modules.path: /etc/filebeat/modules.d/*.yml
  reload.enabled: false