version: "3.4"
x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    ports:
     - 9090:9090
    volumes:
     - ./prometheus:/etc/prometheus
     - prometheus_data:/prometheus
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention=30d
    restart: unless-stopped
    logging: *default-logging
    
  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    ports:
      - 3000:3000
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    logging: *default-logging
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:
