- name: kandula_consul_playbook
  hosts: tag_kandula_app_true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - consul

- name: kandula_jenkins_playbook
  hosts: tag_jenkins_true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - jenkins-role


