- name: kandula_playbook
  hosts: tag_kandula_app_true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - consul

- name: kandula_playbook
  hosts: tag_jenkins_slave_true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - docker
  #  - jenkins

- name: kandula_playbook
  hosts: tag_jenkins_server_true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - docker-role
  #  - jenkins-role

# - name: kandula_playbook
#   hosts: tag_prometheus_server_true:&tag_kandula_app_true
#   remote_user: ubuntu
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - docker-role
#     - prometheus
    

# - name: kandula_playbook
#   hosts: tag_elasticsearch_kibana_true
#   remote_user: ubuntu
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - elasticsearch-role
#     - kibana-role

