---
- name: installing elasticsearch gpg key
  become: true
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add 

- name: Installing Elasticsearch repository
  become: true
  shell: sudo apt-add-repository "deb https://artifacts.elastic.co/packages/8.x/apt stable main"

- name: installing updates
  become: true
  shell: sudo apt-get update -yqq

- name: installing kibana and apt-transport-https
  become: true
  shell: sudo apt-get install -yqq kibana apt-transport-https

- name: Copy kibana.yml conf file
  ansible.builtin.copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    force: yes
    owner: root
    group: root
    mode: '0644'

- name: enable kibana service
  become: true
  shell: sudo systemctl enable kibana

- name: start kibana service
  become: true
  shell: sudo systemctl start kibana

- name: copy consul-kibana template
  template:
    dest: /etc/consul.d/kibana.json
    src: kibana.json.j2
    force: yes
    owner: consul
    group: consul
    mode: '0755'
  notify: "restart consul service"