apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kandula # namespace added
  labels:
    app: backend
    env: prod
spec:
  selector:
    app: backend
    env: prod
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
