# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   namespace: kandula # namespace added
#   labels:
#     app: backend
#     # env: prod
# spec:
#   selector:
#     app: backend
#     # env: prod
#   type: LoadBalancer
#   ports:
#     - name: http
#       port: 80
#       targetPort: 5000
#       protocol: TCP
apiVersion: v1
kind: Service
metadata:
  name: kandula-service
  namespace: kandula
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer
  externalTrafficPolicy: Local