apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula
  namespace: kandula # namespace added
  labels:
    app: backend
    # env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      # env: prod
  template:
    metadata:
      labels:
        app: backend
        # env: prod
    spec:
      containers:
      - name: kandula
        image: dvaturi/kandula:latest
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: FLASK_APP
          value: kandula
        - name: SECRET_KEY
          value: kandula123
