---
- name: installing elasticsearch gpg key
  become: true
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add 

- name: Installing Elasticsearch repository
  become: true
  shell: sudo apt-add-repository "deb https://artifacts.elastic.co/packages/8.x/apt stable main"

- name: installing updates
  become: true
  shell: sudo apt-get update -yqq

- name: installing logstash
  become: true
  shell: sudo apt-get install -yqq logstash

- name: copy logstash config file
  copy:
    dest: /etc/logstash/conf.d/logstash.conf
    src: logstash.conf
    mode: '0755'

- name: enable logstash service
  become: true
  shell: sudo systemctl enable logstash

- name: start logstash service
  become: true
  shell: sudo systemctl start logstash
    
- name: copy consul-logstash template
  template:
    dest: /etc/consul.d/logstash.json
    src: logstash.json.j2
    force: yes
    owner: consul
    group: consul
    mode: '0755'
  notify: "restart consul service"