---
- name: Install Cosnul on Kubernetes 1/3
  become: true
  shell: kubectl create secret generic consul-gossip-encryption-key --from-literal=key="uDBV4e+LbFW3019YKPxIrg=="

- name: Install Cosnul on Kubernetes 2/3
  become: true
  shell: helm repo add hashicorp https://helm.releases.hashicorp.com

- name: Install Cosnul on Kubernetes 3/3
  become: true
  shell: helm install consul hashicorp/consul -f values_consul.yaml

- name: Copy coredns.yaml file
  ansible.builtin.copy:
    src: coredns.yaml
    dest: ./coredns.yaml
    force: yes
    owner: root
    group: root
    mode: '0644'

- name: apply changes for coredns
  become: true
  shell: kubectl apply -f ./coredns.yaml

- name: Copy values_node-exporter.yaml file
  ansible.builtin.copy:
    src: values_node-exporter.yaml
    dest: ./values_node-exporter.yaml
    force: yes
    owner: root
    group: root
    mode: '0644'

- name: installing node exporter 1/2
  become: true
  shell: helm repo add bitnami https://charts.bitnami.com/bitnami

- name: installing node exporter 2/2
  become: true
  shell: helm install k8s bitnami/node-exporter -f values_node-exporter.yaml  

- name: Copy filebeat.yaml file
  ansible.builtin.copy:
    src: filebeat.yaml
    dest: ./filebeat.yaml
    force: yes
    owner: root
    group: root
    mode: '0644'

- name: apply changes for filebeat
  become: true
  shell: kubectl apply -f filebeat.yaml 
